I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 80, in script
    if newBool:
  File "game/script.rpy", line 80, in <module>
    if newBool:
NameError: name 'newBool' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 80, in script
    if newBool:
  File "C:\Users\Daniel Bassani\Downloads\renpy-7.1.3-sdk\renpy\ast.py", line 1762, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Daniel Bassani\Downloads\renpy-7.1.3-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Daniel Bassani\Downloads\renpy-7.1.3-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 80, in <module>
    if newBool:
NameError: name 'newBool' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
Project Lintahlo 1.0
Sun Mar 10 21:10:50 2019
